sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
cache:
  bundler: true
  directories:
  - node_modules
  - $(npm config get prefix)
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm run build

install:
- npm install

script:


after_success:
- bash deploy.sh

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
